language: ruby
rvm:
- 2.3.1
- 2.3.0
- 2.2.2
script:
- cd test/dummy/
- bundle exec rake railties:install:migrations
- bundle exec rails db:migrate
- cd ../../
- bundle exec rake test
env:
  global:
  - COVERAGE=true
  matrix:
    secure: 0duuoXsaWuDuAsYEDtOU1uH/rUQwaBXBNcZztVExNg8ucMqwvWhRwRDmOEly/Pf5Fn6+ZHJYKaCGHUIBzT5xBGXfLiC8oXnM3au2Xl0YEKR+O9NREqsX9qmxp32G8hGSDdJr7AE/KswEiGoCdkfBF4IzY1HyOkFKrCzzIplCrcTjpjnb0ZYHN/0kcrVKGPk2hLovZ9EjWOnqqjTFDcetQ7Ka5DY9cQ7Gm/rS3HZ8CbPOJvWsF7d9vqtDS9ok/sQIHbLBGODhq30sEouF0+RdRAk5o+QM7QgYBynOTMJh1z16Hw3ePnU1rY9AQoBR3l227utHMR24PP/iv66QcA627PYqYFvuztDykT+j8JD/HQPAfHE+9q5/Bp4Zg3Mz7iz872sPOa3qpGlULSYlC+nZniCe2c93YsHxrvS3AReLNRPq/gzMJuzzuepkEIg4wudVNqcH26AuQwodagW411N3TbKJ/ol8suszvLqLR0bKnAPwX/0iHrMJTD3Ayf+Au03wX1kuhrCyFVp1rKMaFf3S9YFJ3vWv+3F6KX5+5Hpw6IbhcBaLhXJB/4wS3VlxSXd0i1zegE0KB67pRQEyVjPOVEWXoZQuNRPQe2TbpgqEHJG5x2H4UWMyEyKBmer5bG1ZYL4x8exnm8ri3KICuAfRwNv8776SEOlJDf4pvB3ONVQ=
